Traceback (most recent call last):
  File "/var/spool/slurmd/job3009728/slurm_script", line 2, in <module>
    import src.retrieve_SEA_data as retrieve
  File "/net/home/h03/hadpx/MJO/SEAPy/src/retrieve_SEA_data.py", line 4, in <module>
    import iris
  File "/opt/scitools/environments/default/2018_05_22-1/lib/python2.7/site-packages/iris/__init__.py", line 110, in <module>
    import iris.cube
  File "/opt/scitools/environments/default/2018_05_22-1/lib/python2.7/site-packages/iris/cube.py", line 46, in <module>
    import iris.analysis
  File "/opt/scitools/environments/default/2018_05_22-1/lib/python2.7/site-packages/iris/analysis/__init__.py", line 59, in <module>
    import scipy.interpolate
  File "/opt/scitools/environments/default/2018_05_22-1/lib/python2.7/site-packages/scipy/interpolate/__init__.py", line 160, in <module>
    from .interpolate import *
  File "/opt/scitools/environments/default/2018_05_22-1/lib/python2.7/site-packages/scipy/interpolate/interpolate.py", line 16, in <module>
    import scipy.linalg
  File "/opt/scitools/environments/default/2018_05_22-1/lib/python2.7/site-packages/scipy/linalg/__init__.py", line 174, in <module>
    from .misc import *
  File "/opt/scitools/environments/default/2018_05_22-1/lib/python2.7/site-packages/scipy/linalg/misc.py", line 5, in <module>
    from .blas import get_blas_funcs
  File "/opt/scitools/environments/default/2018_05_22-1/lib/python2.7/site-packages/scipy/linalg/blas.py", line 155, in <module>
    from scipy.linalg import _fblas
ImportError: libptf77blas.so.3: cannot open shared object file: No such file or directory
